export default defineEventHandler((event) => {
  return [
    //Rain
    {
      id: 1,
      title: "Rain & Thunders",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Refreshing Rain",
          soundIcon: "/images/Extra Sounds img/Rain/Refreshing Rain.png",
          sound: "/sounds/Rain/Refreshing Rain.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain in Window",
          soundIcon: "/images/Extra Sounds img/Rain/Rain in Window.png",
          sound: "/sounds/Rain/Rain in Window.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain in Forest",
          soundIcon: "/images/Extra Sounds img/Rain/Rain in Forest.png",
          sound: "/sounds/Rain/Rain in Forest.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain on Leaves",
          soundIcon: "/images/Extra Sounds img/Rain/Rain on Leaves.png",
          sound: "/sounds/Rain/Rain on Leaves.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain under Umbrella",
          soundIcon: "/images/Extra Sounds img/Rain/Rain under Umbrella.png",
          sound: "/sounds/Rain/Rain under Umbrella.mp3",
          isLocked: true,
          premiumCard: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Thunderstorm",
          soundIcon: "/images/Extra Sounds img/Rain/Thunderstorm.png",
          sound: "/sounds/Rain/Thunderstorm.mp3",
          isLocked: true,
          premiumCard: true,
        },
      ],
    },
    //Nature
    {
      id: 2,
      title: "Nature",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Peaceful Night",
          soundIcon: "/images/Extra Sounds img/Nature/Peaceful Night.png",
          sound: "/sounds/Nature/Peaceful Night.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Vivid Creek",
          soundIcon: "/images/Extra Sounds img/Nature/Vivid Creek.png",
          sound: "/sounds/Nature/Vivid Creek.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Ocean",
          soundIcon: "/images/Extra Sounds img/Nature/Ocean.png",
          sound: "/sounds/Nature/Ocean.mp3",
          isLocked: true,
          premiumCard: true,
        },

        {
          soundId: Math.random(),
          volume: 1,
          name: "Autumn Woods",
          soundIcon: "/images/Extra Sounds img/Nature/Autumn Woods.png",
          sound: "/sounds/Nature/Autumn Woods.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Quiet Cave",
          soundIcon: "/images/Extra Sounds img/Nature/Quiet Cave.png",
          sound: "/sounds/Nature/Quiet Cave.mp3",
          isLocked: true,
          premiumCard: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Desert",
          soundIcon: "/images/Extra Sounds img/Nature/Desert.png",
          sound: "/sounds/Nature/Desert.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Lake",
          soundIcon: "/images/Extra Sounds img/Nature/Lake.png",
          sound: "/sounds/Nature/Lake.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Fire",
          soundIcon: "/images/Extra Sounds img/Nature/Fire.png",
          sound: "/sounds/Nature/Fire.mp3",
          isLocked: false,
        },
      ],
    },
    //Animals
    {
      id: 3,
      title: "Animals",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Relax/Relax.jpg",
          sound: "/sounds/Relax/Relax.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Relax/Reflection.jpg",
          sound: "/sounds/Relax/Reflection.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Relax/Calm.jpg",
          sound: "/sounds/Relax/Calm.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Relax/Hope.jpg",
          sound: "/sounds/Relax/Hope.mp3",
          isLocked: true,
          premiumCard: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Relax/Serenity.jpg",
          sound: "/sounds/Relax/Serenity.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Relax/Inspiration.jpg",
          sound: "/sounds/Relax/Inspiration.mp3",
          isLocked: true,
          premiumCard: true,
        },
      ],
    },
    //Transport
    {
      id: 4,
      title: "Transport",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Transport/Vintage Train.jpg",
          sound: "/sounds/Transport/Vintage Train.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Transport/Above the Sky.jpg",
          sound: "/sounds/Transport/Above the Sky.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Transport/Soothing Ride.jpg",
          sound: "/sounds/Transport/Soothing Ride.mp3",
          isLocked: true,
          premiumCard: true,
        },
      ],
    },
    //Music & Instruments
    {
      id: 5,
      title: "Music & Instruments",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/White Noise.jpg",
          sound: "/sounds/Noise/White Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/Brown Noise.jpg",
          sound: "/sounds/Noise/Brown Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/Pink Noise.jpg",
          sound: "/sounds/Noise/Pink Noise.mp3",
          isLocked: true,
          premiumCard: true,
        },
      ],
    },
    //ASMR
    {
      id: 6,
      title: "ASMR",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/White Noise.jpg",
          sound: "/sounds/Noise/White Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/Brown Noise.jpg",
          sound: "/sounds/Noise/Brown Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/Pink Noise.jpg",
          sound: "/sounds/Noise/Pink Noise.mp3",
          isLocked: true,
          premiumCard: true,
        },
      ],
    },
    //Lullabies
    {
      id: 7,
      title: "Lullabies",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/White Noise.jpg",
          sound: "/sounds/Noise/White Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/Brown Noise.jpg",
          sound: "/sounds/Noise/Brown Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "",
          soundIcon: "/images/Noise/Pink Noise.jpg",
          sound: "/sounds/Noise/Pink Noise.mp3",
          isLocked: true,
          premiumCard: true,
        },
      ],
    },
  ];
});
