export default defineEventHandler((event) => {
  return [
    //Rain
    {
      id: 1,
      title: "Rain & Thunders",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Refreshing Rain",
          soundIcon: "/images/Extra Sounds img/Rain/Refreshing Rain.png",
          sound: "/sounds/Rain/Refreshing Rain.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain in Window",
          soundIcon: "/images/Extra Sounds img/Rain/Rain in Window.png",
          sound: "/sounds/Rain/Rain in Window.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain in Forest",
          soundIcon: "/images/Extra Sounds img/Rain/Rain in Forest.png",
          sound: "/sounds/Rain/Rain in Forest.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain on Leaves",
          soundIcon: "/images/Extra Sounds img/Rain/Rain on Leaves.png",
          sound: "/sounds/Rain/Rain on Leaves.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Rain under Umbrella",
          soundIcon: "/images/Extra Sounds img/Rain/Rain under Umbrella.png",
          sound: "/sounds/Rain/Rain under Umbrella.mp3",
          isLocked: true,
          premiumSound: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Thunderstorm",
          soundIcon: "/images/Extra Sounds img/Rain/Thunderstorm.png",
          sound: "/sounds/Rain/Thunderstorm.mp3",
          isLocked: true,
          premiumSound: true,
        },
      ],
    },
    //Nature
    {
      id: 2,
      title: "Nature",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Peaceful Night",
          soundIcon: "/images/Extra Sounds img/Nature/Peaceful Night.png",
          sound: "/sounds/Nature/Peaceful Night.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Vivid Creek",
          soundIcon: "/images/Extra Sounds img/Nature/Vivid Creek.png",
          sound: "/sounds/Nature/Vivid Creek.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Ocean",
          soundIcon: "/images/Extra Sounds img/Nature/Ocean.png",
          sound: "/sounds/Nature/Ocean.mp3",
          isLocked: false,
        },

        {
          soundId: Math.random(),
          volume: 1,
          name: "Autumn Woods",
          soundIcon: "/images/Extra Sounds img/Nature/Autumn Woods.png",
          sound: "/sounds/Nature/Autumn Woods.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Quiet Cave",
          soundIcon: "/images/Extra Sounds img/Nature/Quiet Cave.png",
          sound: "/sounds/Nature/Quiet Cave.mp3",
          isLocked: true,
          premiumSound: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Desert",
          soundIcon: "/images/Extra Sounds img/Nature/Desert.png",
          sound: "/sounds/Nature/Desert.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Lake",
          soundIcon: "/images/Extra Sounds img/Nature/Lake.png",
          sound: "/sounds/Nature/Lake.mp3",
          isLocked: false,
        },
      ],
    },
    //Animals
    {
      id: 3,
      title: "Animals",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Birds",
          soundIcon: "/images/Extra Sounds img/Animals/bird.png",
          sound: "/sounds/Extra Sounds/Animals/birds.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Forest birds",
          soundIcon: "/images/Extra Sounds img/Animals/forest-bird.png",
          sound: "/sounds/Extra Sounds/Animals/forest-birds.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Owl",
          soundIcon: "/images/Extra Sounds img/Animals/owl.png",
          sound: "/sounds/Extra Sounds/Animals/owls.mp3",
          isLocked: true,
          premiumSound: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Wolve",
          soundIcon: "/images/Extra Sounds img/Animals/wolve.png",
          sound: "/sounds/Extra Sounds/Animals/wolves.mp3",
          isLocked: true,
          premiumSound: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Frog",
          soundIcon: "/images/Extra Sounds img/Animals/frog.png",
          sound: "/sounds/Extra Sounds/Animals/frogs.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Cricket",
          soundIcon: "/images/Extra Sounds img/Animals/cricket.png",
          sound: "/sounds/Extra Sounds/Animals/crickets.mp3",
          isLocked: false,
        },
      ],
    },
    //ASMR
    {
      id: 4,
      title: "ASMR",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Breathing",
          soundIcon: "/images/Extra Sounds img/ASMR/breathing.png",
          sound: "/sounds/Extra Sounds/ASMR/breathing.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Car engine",
          soundIcon: "/images/Extra Sounds img/ASMR/car_engine.png",
          sound: "/sounds/Extra Sounds/ASMR/car_engine.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Cat purring",
          soundIcon: "/images/Extra Sounds img/ASMR/cat_purring.png",
          sound: "/sounds/Extra Sounds/ASMR/cat_purring.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Chewing",
          soundIcon: "/images/Extra Sounds img/ASMR/chewing.png",
          sound: "/sounds/Extra Sounds/ASMR/chewing.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Fire",
          soundIcon: "/images/Extra Sounds img/ASMR/fire.png",
          sound: "/sounds/Extra Sounds/ASMR/fire.mp3",
          isLocked: true,
          premiumSound: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Hair clipper",
          soundIcon: "/images/Extra Sounds img/ASMR/hair_clipper.png",
          sound: "/sounds/Extra Sounds/ASMR/hair_clipper.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Page turning",
          soundIcon: "/images/Extra Sounds img/ASMR/page_turning.png",
          sound: "/sounds/Extra Sounds/ASMR/page_turning.mp3",
          isLocked: false,
        },
      ],
    },
    //Transport
    {
      id: 5,
      title: "Transport",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Car",
          soundIcon: "/images/Extra Sounds img/Transport/car.png",
          sound: "/sounds/Transport/Soothing Ride.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Train",
          soundIcon: "/images/Extra Sounds img/Transport/train.png",
          sound: "/sounds/Transport/Vintage Train.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Plane",
          soundIcon: "/images/Extra Sounds img/Transport/plane.png",
          sound: "/sounds/Transport/Above the Sky.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Boat",
          soundIcon: "/images/Extra Sounds img/Transport/boat.png",
          sound: "/sounds/Transport/boat.mp3",
          isLocked: true,
          premiumSound: true,
        },
      ],
    },
    //Music & Instruments
    {
      id: 6,
      title: "Music & Instruments",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "Piano 1",
          soundIcon: "/images/Extra Sounds img/Music&Instruments/piano.png",
          sound: "/sounds/Relax/Piano.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Piano 2",
          soundIcon: "/images/Extra Sounds img/Music&Instruments/piano.png",
          sound: "/sounds/Relax/Piano2.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Harp",
          soundIcon: "/images/Extra Sounds img/Music&Instruments/harp.png",
          sound: "/sounds/Relax/Inspiration.mp3",
          isLocked: true,
          premiumSound: true,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Stones",
          soundIcon: "/images/Extra Sounds img/Music&Instruments/stones.png",
          sound: "/sounds/Relax/Calm.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Flower",
          soundIcon: "/images/Extra Sounds img/Music&Instruments/flower.png",
          sound: "/sounds/Relax/Serenity.mp3",
          isLocked: false,
        },
      ],
    },
    //Noise
    {
      id: 7,
      title: "Noise",
      extraSound: [
        {
          soundId: Math.random(),
          volume: 1,
          name: "White Noise",
          soundIcon: "/images/Extra Sounds img/Noise/noise.png",
          sound: "/sounds/Noise/White Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Brown Noise",
          soundIcon: "/images/Extra Sounds img/Noise/noise.png",
          sound: "/sounds/Noise/Brown Noise.mp3",
          isLocked: false,
        },
        {
          soundId: Math.random(),
          volume: 1,
          name: "Pink Noise",
          soundIcon: "/images/Extra Sounds img/Noise/noise.png",
          sound: "/sounds/Noise/Pink Noise.mp3",
          isLocked: true,
          premiumSound: true,
        },
      ],
    },
  ];
});
